
const DISCOUNT_TYPE_FLAT_PER_PRODUCT = 1;
const DISCOUNT_TYPE_PCT_PER_PRODUCT = 2;
const DISCOUNT_TYPE_BONUS_PRODUCT = 3;
const DISCOUNT_TYPE_FLAT_WHEN_MIN_QTY = 4;
const DISCOUNT_TYPE_PCT_WHEN_MIN_QTY = 5;
const DISCOUNT_TYPE_MEMBERSHIP_PRICE_OFF = 6;
const DISCOUNT_TYPE_PCT_WHEN_MIN_TXN_AMT = 7;
const DISCOUNT_TYPE_FLAT_WHEN_MIN_TXN_AMT = 8;
const DISCOUNT_TYPE_PCT_WHEN_MIN_QTY_PER_TXN = 9;
const DISCOUNT_TYPE_FLAT_WHEN_MIN_QTY_PER_TXN = 10;

module.exports = {
  'DISCOUNT_TYPE_FLAT_PER_PRODUCT': DISCOUNT_TYPE_FLAT_PER_PRODUCT,
  'DISCOUNT_TYPE_PCT_PER_PRODUCT': DISCOUNT_TYPE_PCT_PER_PRODUCT,
  'DISCOUNT_TYPE_BONUS_PRODUCT': DISCOUNT_TYPE_BONUS_PRODUCT,
  'DISCOUNT_TYPE_FLAT_WHEN_MIN_QTY': DISCOUNT_TYPE_FLAT_WHEN_MIN_QTY,
  'DISCOUNT_TYPE_PCT_WHEN_MIN_QTY': DISCOUNT_TYPE_PCT_WHEN_MIN_QTY,
  'DISCOUNT_TYPE_MEMBERSHIP_PRICE_OFF': DISCOUNT_TYPE_MEMBERSHIP_PRICE_OFF,
  'DISCOUNT_TYPE_PCT_WHEN_MIN_TXN_AMT': DISCOUNT_TYPE_PCT_WHEN_MIN_TXN_AMT,
  'DISCOUNT_TYPE_FLAT_WHEN_MIN_TXN_AMT': DISCOUNT_TYPE_FLAT_WHEN_MIN_TXN_AMT,
  'DISCOUNT_TYPE_PCT_WHEN_MIN_QTY_PER_TXN': DISCOUNT_TYPE_PCT_WHEN_MIN_QTY_PER_TXN, // eslint-disable-line
  'DISCOUNT_TYPE_FLAT_WHEN_MIN_QTY_PER_TXN': DISCOUNT_TYPE_FLAT_WHEN_MIN_QTY_PER_TXN, // eslint-disable-line
};
