/**
 * Error Status Code module.
 * @module helpers/ErrorStatusCode
 * @author Prashant Balan <prash.balan@theweflex.com>
 */

const ERR_TXN_GROUP_BUY_QTY = 'ERR_TXN_GROUP_BUY_QTY_CANNOT_BE_MORE_THAN_1';
const ERR_TXN_PAYMENT_TYPE_NOT_FOUND = 'ERR_TXN_PAYMENT_TYPE_NOT_FOUND';
const ERR_TXN_VENUE_PAYMENT_TYPE_NOT_FOUND =
  'ERR_TXN_VENUE_PAYMENT_TYPE_NOT_FOUND';
const ERR_TXN_PAYMENT_TYPE_NOT_AVAILABLE = 'ERR_TXN_PAYMENT_TYPE_NOT_AVAILABLE';
const ERR_TXN_NOT_FOUND = 'ERR_TXN_NOT_FOUND';
const ERR_CARD_DEPOSIT_HISTORY_MIN_DEPOSIT_GT_0 =
  'ERR_CARD_DEPOSIT_HISTORY_MIN_DEPOSIT_GT_0';

module.exports = {
  'ERR_TXN_GROUP_BUY_QTY': ERR_TXN_GROUP_BUY_QTY,
  'ERR_TXN_PAYMENT_TYPE_NOT_FOUND': ERR_TXN_PAYMENT_TYPE_NOT_FOUND,
  'ERR_TXN_VENUE_PAYMENT_TYPE_NOT_FOUND': ERR_TXN_VENUE_PAYMENT_TYPE_NOT_FOUND,
  'ERR_TXN_PAYMENT_TYPE_NOT_AVAILABLE': ERR_TXN_PAYMENT_TYPE_NOT_AVAILABLE,
  'ERR_TXN_NOT_FOUND': ERR_TXN_NOT_FOUND,
  'ERR_CARD_DEPOSIT_HISTORY_MIN_DEPOSIT_GT_0':
    ERR_CARD_DEPOSIT_HISTORY_MIN_DEPOSIT_GT_0,
};
